Repository telling-me/tellingme-client, pull requests merged in 2023-08, with the labels that each got.

#79 [feat]: 모두의 공간 1차 pr
  src/apis/answerApi.ts
  src/apis/questionApi.ts
  src/assets/icons/CaretLeft.svg
  src/assets/icons/ChatTearDrop.svg
  src/assets/icons/index.ts
  src/components/core/input/style.ts
  src/components/core/toggle/Toggle.tsx
  src/components/layout/CommonLayout.tsx
  src/components/widget/allanswer/ListAnswer.tsx
  src/components/widget/allanswer/ListAnswers.tsx
  src/components/widget/allanswer/ListFooter.tsx
  src/components/widget/allanswer/ListHeader.tsx
  src/components/widget/allanswer/ListSorts.tsx
  src/components/widget/allanswer/type.ts
  src/components/widget/index.ts
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/signup/create/CreateGenderBirthYear.tsx
  src/configs/path.ts
  src/data/user.ts
  src/hooks/index.ts
  src/hooks/mutations/answer.ts
  src/hooks/mutations/index.ts
  src/hooks/queries/answer.ts
  src/hooks/queries/index.ts
  src/hooks/queries/question.ts
  src/hooks/useFormatDateArrToStr.ts
  src/pages/PageRouter.tsx
  src/pages/app/allanswer/AllAnswerListPage.tsx
  src/pages/app/allanswer/AllAnswerPage.tsx
  src/pages/app/index.ts
  src/stores/type.ts
  src/stores/useCommunicationStore.ts
Labels: feat

#81 [feat]: 소통공간 -> 답변보기 이어지는 모달창 구현
  src/apis/answerApi.ts
  src/assets/icons/Siren.svg
  src/assets/icons/index.ts
  src/components/core/button/style.ts
  src/components/layout/CommonLayout.tsx
  src/components/widget/allanswer/ListAnswer.tsx
  src/components/widget/index.ts
  src/components/widget/main/AccuseModal.tsx
  src/components/widget/main/AnswerModal.tsx
  src/components/widget/main/EmotionModal.tsx
  src/components/widget/main/Question.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/configs/apple.ts
  src/hooks/mutations/answer.ts
  src/hooks/queries/answer.ts
  src/hooks/queries/index.ts
  src/hooks/queries/question.ts
Labels: feat

#85 [fix]: apple 회원탈퇴 config 변경
  src/components/widget/setting/Withdrawal.tsx
Labels: fix

#86 [fix]: 회원탈퇴 url 디버깅용
  src/pages/signup/WithdrawApplePage.tsx
Labels: fix

#87 [fix]: 회원탈퇴 url location값 hash split 변경
  src/pages/signup/WithdrawApplePage.tsx
Labels: fix

#88 [fix]: 회원탈퇴 hash값 state로 변경
  src/apis/userApi.ts
  src/components/widget/setting/Withdrawal.tsx
  src/hooks/mutations/user.ts
  src/pages/signup/WithdrawApplePage.tsx
Labels: fix

#89 [fix]: 회원탈퇴 임시 console출력
  src/hooks/mutations/user.ts
  src/pages/signup/WithdrawApplePage.tsx
Labels: fix

#90 [fix]: 임시 애플 회원탈퇴 navigate
  src/components/widget/setting/Withdrawal.tsx
Labels: fix

#91 [feat]: 모두의 공간 2차 pr
  .gitignore
  package-lock.json
  package.json
  src/components/core/loading/Loading.tsx
  src/components/widget/allanswer/ListAnswer.tsx
  src/components/widget/allanswer/ListAnswers.tsx
  src/components/widget/allanswer/ListFooter.tsx
  src/components/widget/allanswer/ListSorts.tsx
  src/components/widget/allanswer/type.ts
  src/components/widget/common/Header.tsx
  src/components/widget/index.ts
  src/components/widget/myanswer/CardView.tsx
  src/components/widget/myanswer/CardViewCard.tsx
  src/components/widget/myanswer/ListViewButton.tsx
  src/components/widget/myanswer/NormalListButton.tsx
  src/components/widget/myanswer/Ready.tsx
  src/components/widget/myanswer/SlideListButton.tsx
  src/components/widget/myanswer/Table.tsx
  src/components/widget/myanswer/TableHeader.tsx
  src/components/widget/myanswer/type.ts
  src/hooks/mutations/answer.ts
  src/hooks/queries/answer.ts
  src/pages/app/allanswer/AllAnswerListPage.tsx
  src/pages/app/allanswer/AllAnswerPage.tsx
  src/pages/app/myanswer/MyAnswerPage.tsx
  src/setupProxy.js
  src/stores/type.ts
  src/stores/useCommunicationStore.ts
  vercel.json
Labels: style, fix, feat

#92 [feat]: 신고 모달창 response 분기처리
  src/components/widget/main/AccuseModal.tsx
  src/components/widget/main/AnswerModal.tsx
  src/components/widget/main/QuestionWriteModal.tsx
Labels: feat

#93 [fix]: 모두의 공간 3차 pr
  src/components/widget/allanswer/ListAnswer.tsx
  src/components/widget/allanswer/ListAnswers.tsx
  src/components/widget/allanswer/type.ts
  src/components/widget/main/AnswerModal.tsx
  src/stores/type.ts
  src/stores/useCommunicationStore.ts
Labels: fix

#96 [fix]: 2차 QA - 박성오
  src/apis/userApi.ts
  src/components/layout/CommonLayout.tsx
  src/components/widget/common/Header.tsx
  src/components/widget/landing/LandingBrand.tsx
  src/components/widget/main/AccuseModal.tsx
  src/components/widget/main/AnswerModal.tsx
  src/components/widget/main/EmotionModal.tsx
  src/components/widget/main/EmotionText.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/setting/Withdrawal.tsx
  src/hooks/mutations/user.ts
  src/pages/app/allanswer/AllAnswerListPage.tsx
  src/pages/signup/WithdrawApplePage.tsx
Labels: style, fix, feat

#97 [fix]: 2차 QA (1)
  src/assets/icons/Columns.svg
  src/assets/icons/Rows.svg
  src/components/core/button/style.ts
  src/components/core/tooltip/ToolTip.tsx
  src/components/core/tooltip/style.ts
  src/components/core/tooltip/type.ts
  src/components/widget/common/Footer.tsx
  src/components/widget/common/Header.tsx
  src/components/widget/main/ContinuousDate.tsx
  src/components/widget/main/EmotionModal.tsx
  src/components/widget/main/Question.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/myanswer/TableHeader.tsx
  src/components/widget/setting/PrivacyPolicy.tsx
  src/components/widget/setting/SettingContent.tsx
  src/components/widget/setting/SettingMenu.tsx
  src/components/widget/setting/TermsOfService.tsx
  src/pages/app/myanswer/MyAnswerPage.tsx
Labels: style, fix, feat

#98 [fix]: 2차 QA (2)
  src/assets/icons/Entrance.svg
  src/assets/icons/MyAnswer.svg
  src/assets/icons/SliderLeft.svg
  src/assets/icons/SliderRight.svg
  src/assets/icons/index.ts
  src/components/core/loading/Loading.tsx
  src/components/widget/allanswer/ListAnswers.tsx
  src/components/widget/main/AccuseModal.tsx
  src/components/widget/main/ContinuousDate.tsx
  src/components/widget/myanswer/CardView.tsx
  src/components/widget/myanswer/CardViewCard.tsx
  src/components/widget/setting/ModifyMyInfo.tsx
  src/components/widget/setting/SettingMenu.tsx
  src/components/widget/signup/create/TermsOfServiceModal.tsx
  src/data/docs.ts
  src/pages/app/allanswer/AllAnswerPage.tsx
Labels: style, fix, feat

#99 [fix]: 2차 QA (3)
  src/apis/answerApi.ts
  src/components/layout/CommonLayout.tsx
  src/components/widget/landing/LandingAnswer.tsx
  src/components/widget/landing/LandingEmotion.tsx
  src/components/widget/landing/LandingQuestion.tsx
  src/components/widget/myanswer/CardView.tsx
  src/data/docs.ts
  src/pages/app/allanswer/AllAnswerPage.tsx
  src/pages/app/myanswer/MyAnswerPage.tsx
Labels: style, feat

#100 [fix]: 2차 QA (4)
  src/assets/icons/Columns.svg
  src/assets/icons/Rows.svg
Labels: style

#101 [fix]: 2차 QA (5)
  src/components/widget/allanswer/ListHeader.tsx
  src/components/widget/myanswer/CardViewCard.tsx
  src/pages/app/allanswer/AllAnswerListPage.tsx
Labels: fix

#104 [feat]: RN message 받는 event 구현
  src/pages/app/main/MainPage.tsx
  src/pages/signup/SignUpPage.tsx
Labels: feat
