Repository telling-me/tellingme-client, pull requests merged in 2023-09, with the labels that each got.

#112 [feat]: QA + 세팅 페이지 프로필 + 토스트 컴포넌트
  src/apis/userApi.ts
  src/assets/icons/MyInfo.svg
  src/assets/icons/MyLibrary.svg
  src/assets/icons/Premium.svg
  src/assets/icons/QnA.svg
  src/assets/icons/TellingmeBook.svg
  src/assets/icons/index.ts
  src/components/core/index.ts
  src/components/core/modal/OneButtonModal.tsx
  src/components/core/modal/TwoButtonModal.tsx
  src/components/core/modal/index.ts
  src/components/core/modal/type.ts
  src/components/core/toast/Toast.tsx
  src/components/core/toast/index.ts
  src/components/core/toast/style.ts
  src/components/core/toast/type.ts
  src/components/widget/OnlyMobileModal.tsx
  src/components/widget/allanswer/ListAnswers.tsx
  src/components/widget/index.ts
  src/components/widget/main/AccuseModal.tsx
  src/components/widget/main/EmotionModal.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/myanswer/CardViewCard.tsx
  src/components/widget/setting/ModifyMyInfo.tsx
  src/components/widget/setting/SettingMenu.tsx
  src/components/widget/setting/SettingProfile.tsx
  src/components/widget/setting/SettingQuickMenus.tsx
  src/components/widget/setting/Withdrawal.tsx
  src/components/widget/setting/type.ts
  src/hooks/queries/index.ts
  src/hooks/queries/user.ts
  src/pages/admin/AdminReportPage.tsx
  src/pages/newsletter/NewsLetterPage.tsx
Labels: refactor, style, fix, feat

#113 [fix]: 세팅 페이지 프리미엄 처리안된거 수정
  src/components/widget/setting/SettingProfile.tsx
Labels: fix

#119 Develop
  .eslintrc.json
  src/assets/icons/LibraryProp1.svg
  src/assets/icons/LibraryProp2.svg
  src/assets/icons/Question.svg
  src/assets/icons/index.ts
  src/components/widget/common/Header.tsx
  src/components/widget/common/TabBar.tsx
  src/components/widget/index.ts
  src/components/widget/mylibrary/MyLibraryHelpModal.tsx
  src/components/widget/mylibrary/MyLibraryInfo.tsx
  src/components/widget/mylibrary/MyLibraryWeek.tsx
  src/components/widget/mylibrary/type.ts
  src/hooks/useChangeColor.ts
  src/pages/app/mylibrary/MyLibraryPage.tsx
  src/stores/type.ts
  src/stores/useLibraryStore.ts
  src/styles/DefaultTheme.ts
  src/styles/colors/emotion.ts
  src/styles/colors/sub.ts
  src/styles/styled.d.ts
Labels: fix, feat

#121 [feat]: 듀이의 질문 연구소 + 세팅 페이지 문구 변경 + 파비콘 변경
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/components/widget/setting/ModifyMyInfo.tsx
  src/components/widget/setting/SettingContent.tsx
  src/components/widget/setting/SettingContentHeader.tsx
  src/components/widget/setting/SettingMenu.tsx
  src/components/widget/setting/SettingProfile.tsx
  src/pages/setting/SettingPage.tsx
Labels: style, feat
