Repository telling-me/tellingme-client, pull requests merged in 2023-06, with the labels that each got.

#27 [style](#10): 세팅 페이지 PR
  package-lock.json
  package.json
  public/index.html
  src/components/widget/common/TabBar.tsx
  src/firebase-messaging-sw.ts
  src/pages/setting/SettingPage.tsx
Labels: style, feat

#31 [feat]: 회원가입 완료 페이지 붙이기
  src/components/widget/LoginModal.tsx
  src/components/widget/index.ts
  src/components/widget/landing/LandingHeader.tsx
  src/pages/signup/SignUpCompletePage.tsx
  src/pages/signup/SignUpPage.tsx
Labels: feat

#32 [fix]: button contentType 수정
  src/components/widget/main/QuestionWriteModal.tsx
Labels: fix

#35 Fix/#34/exception for undefined
  src/apis/api.ts
  src/apis/userApi.ts
  src/components/widget/main/ContinuousDate.tsx
  src/components/widget/main/EmotionModal.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/myanswer/TableCell.tsx
  src/data/emotion.ts
  src/hooks/mutations/user.ts
  src/hooks/queries/question.ts
  src/styles/styled-components/styled.ts
  src/type/db.ts
Labels: fix

#37 [feat]: seo 메타 태그 적용
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: feat

#39 [feat]: 임시 뉴스레터 구독 취소 추가
  src/apis/userApi.ts
  src/configs/path.ts
  src/hooks/mutations/index.ts
  src/hooks/mutations/user.ts
  src/pages/PageRouter.tsx
  src/pages/newsletter/NewsLetterUnsubscribeCompletePage.tsx
  src/pages/newsletter/NewsLetterUnsubscribePage.tsx
  src/pages/newsletter/index.ts
Labels: feat

#40 [feat]: 네이버 서치어드바이저 등록
  public/index.html
Labels: feat

#42 [feat]: 파이어 베이스 warning 지우기
  public/firebase-messaging-sw.js
  public/index.html
  src/components/widget/signup/SignUpBottomButton.tsx
  src/components/widget/signup/SignUpTitle.tsx
  src/firebase-messaging-sw.ts
  src/pages/404/ErrorPage.tsx
  src/pages/newsletter/NewsLetterCompletePage.tsx
  src/pages/newsletter/NewsLetterPage.tsx
Labels: style, feat

#43 [feat]: 세팅페이지 이용약관 추가
  src/assets/icons/Pencil.svg
  src/assets/icons/index.ts
  src/components/widget/setting/PrivacyPolicy.tsx
  src/components/widget/setting/TermsOfService.tsx
  src/components/widget/signup/create/CreatePurpose.tsx
  src/data/docs.ts
Labels: style, feat

#45 [fix]: robots disallow 설정 및 sitemap 생성
  public/index.html
  public/robots.txt
  public/sitemap.xml
Labels: fix

#46 [fix]: firebase 모바일 오류 해결
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/App.tsx
  src/firebase-messaging-sw.ts
Labels: fix

#49 [feat]: proxy 주소 변경
  package.json
  vercel.json
Labels: feat

#50 [feat]: 로그인 & 회원가입 페이지 QA
  package-lock.json
  package.json
  src/assets/icons/Apple.svg
  src/assets/icons/Kakao.svg
  src/assets/icons/index.ts
  src/components/core/button/IconButton.tsx
  src/components/core/button/style.ts
  src/components/core/checkbox/CheckBox.tsx
  src/components/core/checkbox/CheckSquare.tsx
  src/components/core/checkbox/style.ts
  src/components/core/checkbox/type.ts
  src/components/core/index.ts
  src/components/core/loading/Loading.tsx
  src/components/core/loading/index.ts
  src/components/core/loadingdots/LoadingDots.tsx
  src/components/core/loadingdots/index.ts
  src/components/widget/LoginModal.tsx
  src/components/widget/setting/PrivacyPolicy.tsx
  src/components/widget/setting/TermsOfService.tsx
  src/components/widget/signup/SignUpBottomButton.tsx
  src/components/widget/signup/SignUpTitle.tsx
  src/components/widget/signup/create/CreateTermsOfService.tsx
  src/components/widget/signup/create/TermsOfServiceModal.tsx
  src/components/widget/signup/type.ts
  src/data/docs.ts
  src/pages/newsletter/NewsLetterPage.tsx
  src/pages/signup/SignUpPage.tsx
Labels: style, fix, feat

#52 Feature/#48/qa mj
  src/components/core/choicechips/ChoiceChips.tsx
  src/components/core/dropdown/Dropdown.tsx
  src/components/core/dropdown/style.ts
  src/components/widget/setting/ModifyMyInfo.tsx
  src/components/widget/setting/SettingContentHeader.tsx
  src/components/widget/setting/SettingMenu.tsx
  src/components/widget/setting/modify/ModifyGender.tsx
  src/components/widget/setting/modify/ModifyPurpose.tsx
  src/components/widget/signup/create/CreateJob.tsx
  src/hooks/mutations/user.ts
  src/hooks/queries/userInfo.ts
Labels: style, fix, feat

#53 [feat]: 500에러 redirect 구현 및 dev 페이지 생성
  src/apis/api.ts
  src/apis/apis.ts
  src/apis/devApi.ts
  src/configs/path.ts
  src/pages/404/Error404Page.tsx
  src/pages/404/index.ts
  src/pages/500/Error500Page.tsx
  src/pages/PageRouter.tsx
  src/pages/dev/DevPage.tsx
  src/pages/dev/index.ts
  src/pages/index.ts
Labels: feat

#54 [fix]: 푸터 아이콘 url 변경
  public/index.html
  src/components/widget/landing/LandingFooter.tsx
  src/pages/newsletter/NewsLetterUnsubscribeCompletePage.tsx
  src/pages/newsletter/NewsLetterUnsubscribePage.tsx
Labels: fix

#55 Fix/#47/qa dev seongoh
  src/assets/icons/AllAnswer.svg
  src/assets/icons/Home.svg
  src/assets/icons/MyAnswer.svg
  src/assets/icons/index.ts
  src/components/widget/common/TabBar.tsx
Labels: style

#57 [fix]: 2023.06.06(수)까지 확인된 개발 QA
  src/assets/icons/Info.svg
  src/assets/icons/ToolTipTriangle.svg
  src/assets/icons/ToolTipTriangle2.svg
  src/assets/icons/index.ts
  src/components/core/button/IconButton.tsx
  src/components/core/input/Input.tsx
  src/components/core/tooltip/ToolTip.tsx
  src/components/core/tooltip/style.ts
  src/components/core/tooltip/type.ts
  src/components/widget/common/Footer.tsx
  src/components/widget/index.ts
  src/components/widget/myanswer/NoneData.tsx
  src/components/widget/setting/ModifyMyInfo.tsx
  src/components/widget/setting/SettingContentHeader.tsx
  src/components/widget/setting/SettingMenu.tsx
  src/components/widget/setting/Withdrawal.tsx
  src/components/widget/signup/SignUpBottomButton.tsx
  src/components/widget/signup/SignUpTitle.tsx
  src/components/widget/signup/create/CreateTermsOfService.tsx
  src/components/widget/signup/create/TermsOfServiceModal.tsx
  src/data/docs.ts
  src/hooks/mutations/user.ts
  src/pages/landing/LandingPage.tsx
  src/pages/newsletter/NewsLetterPage.tsx
  src/pages/setting/SettingPage.tsx
Labels: style, fix, feat

#58 Fix/#47/qa dev seongoh
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/index.html
  public/robots.txt
  public/sitemap.xml
  src/apis/api.ts
  src/assets/icons/AllAnswer.svg
  src/assets/icons/Home.svg
  src/assets/icons/LandingEmotionBg.svg
  src/assets/icons/MyAnswer.svg
  src/components/layout/AppleLayout.tsx
  src/components/layout/KakaoLayout.tsx
  src/components/widget/common/Header.tsx
  src/components/widget/common/TabBar.tsx
  src/components/widget/index.ts
  src/components/widget/landing/LandingAnswer.tsx
  src/components/widget/landing/LandingBrand.tsx
  src/components/widget/landing/LandingCatchPhrase.tsx
  src/components/widget/landing/LandingEmotion.tsx
  src/components/widget/landing/LandingFooter.tsx
  src/components/widget/landing/LandingHeader.tsx
  src/components/widget/landing/LandingQuestion.tsx
  src/components/widget/main/ContinuousDate.tsx
  src/components/widget/main/EmotionModal.tsx
  src/components/widget/main/MainBackground.tsx
  src/components/widget/main/Question.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/myanswer/TableCell.tsx
  src/configs/path.ts
  src/pages/403/Error403Page.tsx
  src/pages/403/index.ts
  src/pages/500/Error500Page.tsx
  src/pages/PageRouter.tsx
  src/pages/app/myanswer/MyAnswerPage.tsx
  src/pages/index.ts
  src/pages/landing/LandingPage.tsx
Labels: style, fix, feat

#59 [fix]: 내답변보기 date 계산 수정
  public/index.html
  src/components/core/button/FloatingButton.tsx
  src/components/core/button/type.ts
  src/components/layout/LandingLayout.tsx
  src/components/widget/common/TabBar.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/myanswer/TableCell.tsx
  src/components/widget/myanswer/type.ts
  src/pages/landing/LandingPage.tsx
Labels: fix

#60 [style]: 모바일 뷰 100vh 수정
  src/App.tsx
  src/components/layout/CommonLayout.tsx
  src/components/widget/landing/LandingBrand.tsx
  src/components/widget/main/EmotionModal.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/setting/ModifyMyInfo.tsx
  src/components/widget/setting/SettingMenu.tsx
  src/pages/403/Error403Page.tsx
  src/pages/404/Error404Page.tsx
  src/pages/500/Error500Page.tsx
  src/pages/app/myanswer/MyAnswerPage.tsx
  src/pages/dev/DevPage.tsx
  src/pages/landing/LandingPage.tsx
  src/pages/newsletter/NewsLetterCompletePage.tsx
  src/pages/newsletter/NewsLetterUnsubscribeCompletePage.tsx
  src/pages/newsletter/NewsLetterUnsubscribePage.tsx
  src/pages/setting/SettingPage.tsx
  src/pages/signup/SignUpCompletePage.tsx
  src/pages/signup/SignUpPage.tsx
Labels: style

#61 Fix/#47/qa dev seongoh
  src/App.tsx
  src/components/core/button/FloatingButton.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/myanswer/ListViewButton.tsx
  src/components/widget/myanswer/TableHeader.tsx
  src/index.tsx
  src/pages/setting/SettingPage.tsx
  src/styles/global.css
Labels: style, fix

#62 [fix]: 2023.06.23(금)까지 확인된 개발 QA
  src/apis/userApi.ts
  src/assets/icons/Info.svg
  src/assets/icons/ToolTipTriangle2.svg
  src/assets/icons/TooltipBottom.svg
  src/assets/icons/TooltipLeft.svg
  src/assets/icons/TooltipRight.svg
  src/assets/icons/TooltipTop.svg
  src/assets/icons/index.ts
  src/components/core/dropdown/Dropdown.tsx
  src/components/core/dropdown/type.ts
  src/components/core/tooltip/ToolTip.tsx
  src/components/core/tooltip/style.ts
  src/components/widget/common/Footer.tsx
  src/components/widget/index.ts
  src/components/widget/landing/LandingFooter.tsx
  src/components/widget/myanswer/TableHeader.tsx
  src/components/widget/setting/ModifyMyInfo.tsx
  src/components/widget/setting/SettingContent.tsx
  src/components/widget/setting/SettingContentHeader.tsx
  src/components/widget/setting/SettingHeader.tsx
  src/components/widget/setting/SettingMenu.tsx
  src/components/widget/setting/Withdrawal.tsx
  src/components/widget/setting/modify/ModifyBirth.tsx
  src/components/widget/setting/modify/ModifyGender.tsx
  src/components/widget/setting/modify/ModifyMbti.tsx
  src/components/widget/signup/create/CreateBirthDate.tsx
  src/components/widget/signup/create/CreateGender.tsx
  src/components/widget/signup/create/CreateMbti.tsx
  src/data/docs.ts
  src/data/emotion.ts
  src/hooks/mutations/user.ts
  src/pages/landing/LandingPage.tsx
  src/pages/signup/SignUpPage.tsx
Labels: style, fix, feat

#63 [fix]: 애플 로그인 오류 해결
  src/apis/userApi.ts
  src/hooks/queries/checkId.ts
  src/hooks/queries/oauth.ts
Labels: fix

#64 [feat]: 감정 모달 및 감정 아이콘 듀이 넣기
  src/assets/icons/EmotionAngry.svg
  src/assets/icons/EmotionComplicated.svg
  src/assets/icons/EmotionExcited.svg
  src/assets/icons/EmotionHappy.svg
  src/assets/icons/EmotionLethargic.svg
  src/assets/icons/EmotionLonely.svg
  src/assets/icons/EmotionMeh.svg
  src/assets/icons/EmotionProud.svg
  src/assets/icons/EmotionRelaxed.svg
  src/assets/icons/EmotionSad.svg
  src/assets/icons/EmotionThrilled.svg
  src/assets/icons/EmotionTired.svg
  src/assets/icons/Lock.svg
  src/assets/icons/index.ts
  src/components/widget/main/EmotionIcon.tsx
  src/components/widget/main/EmotionModal.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/myanswer/TableCell.tsx
  src/data/emotion.ts
Labels: style, feat

#65 [feat]: 듀이티콘 제외 듀이 넣기
  src/assets/icons/EmptyDuei.svg
  src/assets/icons/OverhaulDuei.svg
  src/assets/icons/ResearchDuei.svg
  src/assets/icons/SadDuei.svg
  src/assets/icons/SignUpSuccessDuei.svg
  src/assets/icons/index.ts
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/myanswer/NoneData.tsx
  src/components/widget/setting/Withdrawal.tsx
  src/components/widget/signup/create/CreateTermsOfService.tsx
  src/data/user.ts
  src/pages/403/Error403Page.tsx
  src/pages/404/Error404Page.tsx
  src/pages/500/Error500Page.tsx
  src/pages/signup/SignUpCompletePage.tsx
Labels: style, fix, feat

#66 [feat]: 푸시 알림
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/App.tsx
  src/apis/userApi.ts
  src/components/layout/AppleLayout.tsx
  src/components/layout/CheckPushTokenLayout.tsx
  src/components/layout/KakaoLayout.tsx
  src/components/widget/main/ContinuousDate.tsx
  src/components/widget/main/Question.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/setting/ModifyMyInfo.tsx
  src/components/widget/setting/SettingMenu.tsx
  src/components/widget/setting/Withdrawal.tsx
  src/components/widget/signup/SignUpBottomButton.tsx
  src/components/widget/signup/SignUpHeader.tsx
  src/components/widget/signup/SignUpTitle.tsx
  src/components/widget/signup/type.ts
  src/configs/path.ts
  src/firebase-messaging-sw.ts
  src/hooks/index.ts
  src/hooks/mutations/index.ts
  src/hooks/mutations/user.ts
  src/hooks/queries/checkId.ts
  src/hooks/queries/index.ts
  src/hooks/queries/oauth.ts
  src/hooks/queries/signup.ts
  src/hooks/queries/user.ts
  src/pages/PageRouter.tsx
  src/pages/app/myanswer/MyAnswerPage.tsx
  src/pages/newsletter/NewsLetterPage.tsx
  src/pages/newsletter/NewsLetterUnsubscribePage.tsx
  src/pages/signup/SignUpPage.tsx
Labels: feat

#67 [fix]: 푸시 알림 오류 해결
  src/firebase-messaging-sw.ts
Labels: fix

#68 [style]: 듀이티콘 아이콘 변경
  src/assets/icons/LandingAnswer1.svg
  src/assets/icons/LandingAnswer2.svg
  src/assets/icons/LandingAnswer3.svg
  src/assets/icons/LandingAnswer4.svg
  src/assets/icons/LandingAnswerList.svg
  src/assets/icons/LandingEmotionModal.svg
  src/assets/icons/LandingEmotionModalMobile.svg
  src/assets/icons/NotFound.svg
  src/components/widget/landing/LandingEmotion.tsx
  src/components/widget/myanswer/Ready.tsx
Labels: style

#69 [fix]: 2023.06.29(목)까지 확인된 개발 QA
  src/components/widget/landing/LandingAnswer.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/components/widget/myanswer/TableHeader.tsx
  src/components/widget/setting/ModifyMyInfo.tsx
  src/components/widget/setting/PrivacyPolicy.tsx
  src/components/widget/setting/TermsOfService.tsx
  src/data/docs.ts
Labels: style, fix, feat
