Repository telling-me/tellingme-client, pull requests merged in 2023-10, with the labels that each got.

#124 [feat/fix]: 모두의 공간 푸터 & 헤더 수정 + 로그아웃 오류 수정
  src/components/widget/allanswer/ListFooter.tsx
  src/components/widget/setting/SettingMenu.tsx
  src/pages/app/allanswer/AllAnswerPage.tsx
Labels: fix, feat

#127 Develop
  src/components/widget/allanswer/ListFooter.tsx
  src/components/widget/main/NoticeItem.tsx
  src/components/widget/mylibrary/MyLibraryInfo.tsx
  src/components/widget/mylibrary/MyLibraryWeek.tsx
  src/components/widget/setting/SettingMenu.tsx
  src/components/widget/setting/data.ts
  src/pages/app/allanswer/AllAnswerPage.tsx
Labels: style, fix, feat

#132 [feat/fix] : 모두의 공간 문구 수정 & 앱 유도 모달 브라우저에 맞게 수정
  src/components/widget/OnlyMobileModal.tsx
  src/hooks/index.ts
  src/hooks/useCheckAgent.ts
  src/pages/RouteChangeTracker.tsx
  src/pages/app/allanswer/AllAnswerPage.tsx
Labels: fix, feat

#135 [fix]: http GA 연결 해제
  src/pages/RouteChangeTracker.tsx
Labels: fix

#136 [fix]: GA연결
  src/pages/RouteChangeTracker.tsx
Labels: fix

#137 [fix]: google, naver 서치 코드 변경
  public/index.html
  public/robots.txt
Labels: fix
