Repository telling-me/tellingme-client, pull requests merged in 2023-05, with the labels that each got.

#12 Feature/#11/vercel setting
  package-lock.json
  package.json
  src/App.tsx
  src/pages/RouteChangeTracker.tsx
  src/pages/index.ts
Labels: feat

#15 [feat/style](#6): 뉴스레터 추가 PR_2
  src/components/core/input/style.ts
  src/pages/newsletter/NewsLetterPage.tsx
Labels: style, feat

#21 [feat]: 랜딩페이지 구현
  package-lock.json
  package.json
  src/assets/icons/Insta.svg
  src/assets/icons/LandingAnswer1.svg
  src/assets/icons/LandingAnswer2.svg
  src/assets/icons/LandingCatchPhraseCircle.svg
  src/assets/icons/LandingCircle.svg
  src/assets/icons/LandingEmotionBg.svg
  src/assets/icons/LandingEmotionLine.svg
  src/assets/icons/LandingEmotionModal.svg
  src/assets/icons/LandingEmotionModalMobile.svg
  src/assets/icons/LandingPhone.svg
  src/assets/icons/LandingQuestionList.svg
  src/assets/icons/Logo.svg
  src/assets/icons/LogoSmallBubble1.svg
  src/assets/icons/LogoSmallBubble2.svg
  src/assets/icons/LogoSmallBubble3.svg
  src/assets/icons/LogoSmallBubble4.svg
  src/assets/icons/ScrollDown.svg
  src/assets/icons/bubble.svg
  src/assets/icons/index.ts
  src/assets/icons/logo_s1.svg
  src/assets/icons/logo_s2.svg
  src/assets/icons/logo_s3.svg
  src/assets/icons/logo_s4.svg
  src/components/layout/LandingLayout.tsx
  src/components/widget/index.ts
  src/components/widget/landing/LandingAnswer.tsx
  src/components/widget/landing/LandingBrand.tsx
  src/components/widget/landing/LandingCatchPhrase.tsx
  src/components/widget/landing/LandingEmotion.tsx
  src/components/widget/landing/LandingFooter.tsx
  src/components/widget/landing/LandingQuestion.tsx
  src/components/widget/main/MainBackground.tsx
  src/hooks/useWindowSize.ts
  src/pages/landing/LandingPage.tsx
  src/pages/signup/SignUpPage.tsx
  src/styles/ani.ts
  src/styles/gradient.ts
  src/styles/styled-components/styled.ts
  src/utils/mediaQuery.ts
Labels: fix, feat

#22 [fix]: api date 추가
  src/apis/questionApi.ts
  src/components/widget/main/ContinuousDate.tsx
  src/components/widget/main/Question.tsx
  src/components/widget/main/QuestionWriteModal.tsx
  src/hooks/mutations/question.ts
  src/hooks/queries/index.ts
  src/hooks/queries/question.ts
  src/utils/date.ts
Labels: fix
